sudo: required
language: node_js
dist: xenial

node_js:
  - "10.16.3"

services:
  - docker

before_script:
  - sudo apt-get update

script:
  - docker container run --publish 80:80 nginx

after_failure:
  - sudo systemctl status docker.service
  - sudo journalctl